version: '3.1'
services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    restart: always
    volumes:
      - ./clickhouse_database:/var/lib/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks: 
      - public
      
networks:
  public:
    external:
      name: public