services:
  clickhouse:
    image: clickhouse:25.8
    container_name: clickhouse
    restart: always
    volumes:
      - ./clickhouse_database:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse-server/
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "123456"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks: 
      - public

  clickhouse-exporter:
    image: f1yegor/clickhouse-exporter
    container_name: clickhouse-exporter
    restart: always
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
    command: -scrape_uri=http://clickhouse:8123/
    ports:
      - 9116:9116
    networks: 
      - public
      
networks:
  public:
    external: true