version: '3.1'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.2
    container_name: filebeat
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      # 映射到容器中[作为数据源]
      - ./logs:/usr/share/filebeat/logs
      - ./data:/usr/share/filebeat/data
      - ./elk/logs:/home/project/elk/logs
    ports:
      - 19000:19000
    networks: 
      - public
      
networks:
  public:
    external:
      name: public