filebeat.inputs:
  - type: log
    enabled: true
    tags: ["springblade"]
    paths:
      # 当前目录下的所有.log文件
      - /home/project/springblade/log/*/*.log
    multiline.pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{0,3} \[  
    multiline.negate: true
    multiline.match: after
    fields:
      event.dataset: springblade
  - type: log
    enabled: true
    tags: ["nginx"]
    paths:
      # 当前目录下的所有.log文件
      - /home/project/nginx/log/access.log
    fields:
      event.dataset: nginx.access
  - type: log
    enabled: true
    tags: ["nginx"]
    paths:
      # 当前目录下的所有.log文件
      - /home/project/nginx/log/error.log
    fields:
      event.dataset: nginx.error        
  - type: tcp
    enabled: true
    max_message_size: 10MiB
    host: "0.0.0.0:19000"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.dashboards.enabled: false

setup.kibana:
  host: "http://10.10.0.81:5601"

# 不直接传输至ES
# setup.template.name: "filebeat"
# setup.template.pattern: "filebeat-*"
# output.elasticsearch:
#  hosts: ["http://10.0.0.247:9200"]
#  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"

output.logstash:
  hosts: ["10.10.0.81:5044"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
