# Use root/example as user/password credentials
version: '3.1'
services:
  frps:
    image: snowdreamtech/frps:0.52.1
    container_name: frps
    privileged: true
    restart: always
    volumes:
      - ./conf/frps.toml:/etc/frp/frps.toml
      - ./log/:/var/log/
    network_mode: host