services:
  frps:
    image: snowdreamtech/frps:0.62.1
    container_name: frps
    privileged: true
    restart: always
    volumes:
      - ./conf/frps.toml:/etc/frp/frps.toml
      - ./log/:/var/log/
    network_mode: host