# Use root/example as user/password credentials
version: '3.1'
services:
  zookeeper:
    image: 'zookeeper'
    container_name: zookeeper
    restart: always
    ports:
      - '2181:2181'
      - '2888:2888'
      - '3888:3888'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=192.168.6.135:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr
    networks:
      - public

  zookeeper-exporter:
    image: 'bitnami/zookeeper-exporter'
    container_name: zookeeper-exporter
    restart: always
    ports:
      - '9141:9141'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    command: -zk-list 192.168.6.135:2181 -listen 0.0.0.0:9141
    networks:
      - public

networks:
  public:
    external:
      name: public
