version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode
    container_name: namenode
    hostname: namenode
    ports:
      - 9000:9000
      - 9870:9870
    volumes:
      - /data/DockerCompose/Hadoop/hdfs/namenode/:/hadoop/dfs/name/
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ../hadoop.env
    extra_hosts: 
      - "server252:10.0.0.252"
      - "namenode:10.0.0.252"
      - "datanode:10.0.0.252"
      - "historyserver:10.0.0.252"
      - "resourcemanager:10.0.0.252"
    networks: 
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode
    container_name: datanode
    hostname: datanode
    volumes:
      - /data/DockerCompose/Hadoop/hdfs/datanode/:/hadoop/dfs/data/
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    ports:
      - 9864:9864
      - 9866:9866
    env_file:
      - ../hadoop.env
    extra_hosts: 
      - "server252:10.0.0.252"
      - "namenode:10.0.0.252"
      - "datanode:10.0.0.252"
      - "historyserver:10.0.0.252"
      - "resourcemanager:10.0.0.252"
    networks: 
      - hadoop

networks:
 hadoop:
  external:
   name: hadoop