# Use root/example as user/password credentials
version: '3.1'
services:
  v2ray-nginx:
    image: nginx
    container_name: v2ray-nginx
    restart: always
    volumes:
      - ./config/conf.d/:/etc/nginx/conf.d/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/blackip.conf:/etc/nginx/blackip.conf
      - ./share/:/usr/share/nginx/html/
      - ./log/:/var/log/nginx/
      - ./certs/:/etc/ssl/certs/
    environment:
      - NGINX_PORT=80
    ports: 
      - 10820:10820
      - 10810:10810
    networks: 
      - v2ray
  v2ray1:
    image: v2fly/v2fly-core:v4.45.2
    container_name: v2ray1
    restart: always
    volumes:
      - ./config/config1.json:/etc/v2ray/config.json
    ports: 
      - 10821:10821
      - 10811:10811
    networks: 
      - v2ray
  v2ray2:
    image: v2fly/v2fly-core:v4.45.2
    container_name: v2ray2
    restart: always
    volumes:
      - ./config/config2.json:/etc/v2ray/config.json
    ports: 
      - 10822:10821
      - 10812:10811
    networks: 
      - v2ray
  v2ray3:
    image: v2fly/v2fly-core:v4.45.2
    container_name: v2ray3
    restart: always
    volumes:
      - ./config/config3.json:/etc/v2ray/config.json
    ports: 
      - 10823:10821
      - 10813:10811
    networks: 
      - v2ray

networks:
  v2ray:
    driver: bridge