# Use root/example as user/password credentials
version: '3.1'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    networks: 
      - public
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    volumes:
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/node-exporter/proc:/host/proc:ro
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/node-exporter/sys:/host/sys:ro
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/node-exporter/rootfs:/host/rootfs:ro
    ports:
      - 9100:9100
    networks: 
      - public
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: always
    volumes:
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/blackbox_exporter/config:/config
    ports:
      - 9115:9115
    networks: 
      - public
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    volumes:
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/alertmanager/config/:/etc/alertmanager/
    ports:
      - 9093:9093
    networks: 
      - public
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - /tmp/docker-desktop-root/mnt/host/d/DockerCompose/prometheus/grafana/:/var/lib/grafana/
    ports:
      - 3000:3000
    networks: 
      - public
      
networks:
  public:
    external:
      name: public