# Use root/example as user/password credentials
version: '3.1'
services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu:24.04
    restart: always
    entrypoint: "/bin/bash"
    command: 
      - "-c" 
      - "--" 
      - "while true; do sleep 3600; done;"
    volumes: 
      - ./data:/data
    ports: 
      - 30022:22
      - 30080:80
    networks: 
      - public
      
networks:
  public:
    external: true   