version: "3"

services:
  hive:
    image: bde2020/hive
    container_name: hive
    hostname: hive
    ports:
      - 10000:10000
    env_file:
      - ../hadoop.env
    volumes:
      - /data/DockerCompose/Hadoop/hive/config/:/opt/hive/conf/
    extra_hosts: 
      - "server252:10.0.0.252"
      - "namenode:10.0.0.252"
      - "datanode:10.0.0.252"
      - "historyserver:10.0.0.252"
      - "resourcemanager:10.0.0.252"
    networks: 
      - hadoop

networks:
 hadoop:
  external:
   name: hadoop