services:
  mongo0:
    container_name: mongo0
    image: mongo:3.6.23
    restart: always
    command: --replSet replset0
    # command: --replSet replset0 --auth --keyFile /data/mongo.key
    ports:
      - "27017:27017"
    volumes:
      - ./data/db0:/data/db
      # - ./data/mongo.key:/data/mongo.key
    networks:
      - mongo

  mongo1:
    container_name: mongo1
    image: mongo:3.6.23
    restart: always
    command: --replSet replset0
    # command: --replSet replset0 --auth --keyFile /data/mongo.key
    ports:
      - "27117:27017"
    volumes:
      - ./data/db1:/data/db
      # - ./data/mongo.key:/data/mongo.key
    networks:
      - mongo

  mongo2:
    container_name: mongo2
    image: mongo:3.6.23
    restart: always
    command: --replSet replset0
    # command: --replSet replset0 --auth --keyFile /data/mongo.key
    ports:
      - "27217:27017"
    volumes:
      - ./data/db2:/data/db
      # - ./data/mongo.key:/data/mongo.key
    networks:
      - mongo

networks:
  mongo:
    driver: bridge
