# Use root/example as user/password credentials
version: '3.1'

services:

  mongo0:
    container_name: mongo0
    image: mongo:3.6.19
    restart: always
    command: --replSet replset0
    ports: 
    - "27017:27017"
    networks: 
      - mongo

  mongo1:
    container_name: mongo1
    image: mongo:3.6.19
    restart: always
    command: --replSet replset0
    ports: 
    - "27117:27017"
    networks: 
      - mongo

  mongo2:
    container_name: mongo2
    image: mongo:3.6.19
    restart: always
    command: --replSet replset0
    ports: 
    - "27217:27017"
    networks: 
      - mongo

networks:
  mongo:
    driver: bridge

