# Use root/example as user/password credentials
version: '3.1'
services:
  frpc:
    image: snowdreamtech/frpc:0.57.0
    container_name: frpc
    privileged: true
    restart: always
    volumes:
      - ./conf/frpc.toml:/etc/frp/frpc.toml
      - ./log/:/var/log/
    network_mode: host