services:
  frpc:
    image: snowdreamtech/frpc:0.62.1
    container_name: frpc
    privileged: true
    restart: always
    volumes:
      - ./conf/frpc.toml:/etc/frp/frpc.toml
      - ./log/:/var/log/
    network_mode: host