groups:
- name: nodes
  rules:
  - alert: 内存使用率过高
    expr: 100-(node_memory_Buffers_bytes+node_memory_Cached_bytes+node_memory_MemFree_bytes)/node_memory_MemTotal_bytes*100 > 95 
    for: 1m  # 告警持续时间，超过这个时间才会发送给alertmanager
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 内存使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}内存使用率超过95%,当前使用率[{{ $value }}]."

  - alert: cpu使用率过高
    expr: 100-avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by(instance)*100 > 95
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} cpu使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}cpu使用率超过95%,当前使用率[{{ $value }}]."
  
  - alert: 分区使用率过高
    expr: max((node_filesystem_size_bytes{fstype=~"ext.?|xfs"}-node_filesystem_free_bytes{fstype=~"ext.?|xfs"}) *100/(node_filesystem_avail_bytes {fstype=~"ext.?|xfs"}+(node_filesystem_size_bytes{fstype=~"ext.?|xfs"}-node_filesystem_free_bytes{fstype=~"ext.?|xfs"})))by(instance) > 95
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 分区使用率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}分区使用率超过95%,当前使用率[{{ $value }}]."  

  - alert: 磁盘读取速率过高
    expr: max(rate(node_disk_read_bytes_total[1m])) by (instance) /1024/1024 >70
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 磁盘读取速率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}磁盘读取速率超过70MB/s,当前速率[{{ $value }}]MB/s."  

  - alert: 磁盘写入速率过高
    expr: max(rate(node_disk_written_bytes_total[1m])) by (instance) /1024/1024 >70
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 磁盘写入速率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}磁盘写入速率超过70MB/s,当前速率[{{ $value }}]MB/s." 

  - alert: 网络上传速率过高
    expr: max(rate(node_network_transmit_bytes_total[1m])*8) by (instance) /1024/1024 > 100
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 网络上传速率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}网络上传速率超过100MB/s,当前速率[{{ $value }}]MB/s." 
  
  - alert: 网络下载速率过高
    expr: max(rate(node_network_receive_bytes_total[1m])*8) by (instance) /1024/1024 > 100
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 网络下载速率过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}网络下载速率超过100MB/s,当前速率[{{ $value }}]MB/s."

  - alert: 网络连接数过高
    expr: node_netstat_Tcp_CurrEstab > 3000
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 网络连接数过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}网络连接数超过3000,当前连接[{{ $value }}]."

  - alert: 网络待释放连接数过高
    expr: node_sockstat_TCP_tw > 3000
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance }} 网络待释放连接数过高"
      description: "{{ $labels.instance }} of job {{$labels.job}}网络待释放连接数超过3000,当前待释放连接[{{ $value }}]."      

# 尽可能把详细告警信息写入summary标签值，因为告警短信/邮件/钉钉发送的内容使用了summary标签中的值。