# Use root/example as user/password credentials
version: '3.1'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./conf/conf.d/:/etc/nginx/conf.d/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./share/:/usr/share/nginx/html/
      - ./log/:/var/log/nginx/
    environment:
      - NGINX_HOST=test
      - NGINX_PORT=80
    network_mode: host