# Use root/example as user/password credentials
version: '3.1'
services:
  nexus3:
    image: sonatype/nexus3:3.70.3
    container_name: nexus3
    restart: always
    ports: 
      - 18081:8081
    volumes: 
      - ./data:/nexus-data
    privileged: true
    networks: 
      - public

networks:
  public:
    external:
      name: public