# Use root/example as user/password credentials
version: '3.1'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    ports: 
      - 10000:8080
    volumes: 
      - ./jenkins_home:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /usr/bin/docker:/usr/bin/docker
    networks: 
      - jenkins
      
networks:
  jenkins:
    driver: bridge  