# Use root/example as user/password credentials
version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    volumes: 
      - ./data:/var/lib/mysql
      - ./conf/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    privileged: true
    networks: 
      - public
      
  adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    ports:
      - 3406:8080  
    networks: 
      - public

networks:
  public:
    external:
      name: public