# Use root/example as user/password credentials
version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 3306:3306
    volumes: 
      - ./data:/var/lib/mysql
      - ./conf/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    privileged: true
    networks: 
      - public
      
  adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    ports:
      - 3406:8080  
    networks: 
      - public
  
  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    restart: always
    ports: 
      - 9104:9104
    external_links:
      - mysql:mysql
    command:
     - "--mysqld.username=root:root"
     - "--mysqld.address=mysql:3306"
    environment:
      DATA_SOURCE_NAME: root:root@(mysql:3306)/
    networks: 
      - public

networks:
  public:
    external: true