# Use root/example as user/password credentials
version: '3.1'
services:
  sentinel:
    image: bladex/sentinel-dashboard
    container_name: sentinel
    ports: 
      - 8858:8858
    networks: 
      - public

networks:
  public:
    external:
      name: public 
