global:
  #scrape_interval: 15s # 默认15s 全局每次数据收集的间隔
  #evaluation_interval: 15s # 规则扫描时间间隔是15秒，默认不填写是 1分钟
  #scrape_timeout: 5s    #超时时间
  #external_labels: # 用于外部系统标签的，不是用于metrics(度量)数据
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
 
  - job_name: node-exporter
    static_configs:
      - targets: ['10.0.0.1:9091']
        labels:
          instance: localhost