version: "3"

services:
  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "18080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==master"
    extra_hosts: 
      - "server252:10.0.0.252"
      - "namenode:10.0.0.252"
      - "datanode:10.0.0.252"
      - "historyserver:10.0.0.252"
      - "resourcemanager:10.0.0.252"
    networks: 
      - hadoop

  spark-worker:
    image: bde2020/spark-worker
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "18081:8081"
    environment:
      - "SPARK_MASTER=spark://server252:7077"
      - "constraint:node==worker1"
    extra_hosts: 
      - "server252:10.0.0.252"
      - "namenode:10.0.0.252"
      - "datanode:10.0.0.252"
      - "historyserver:10.0.0.252"
      - "resourcemanager:10.0.0.252"
    networks: 
      - hadoop

networks:
 hadoop:
  external:
   name: hadoop