version: "3"

services:
  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - "8090:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==master"
    extra_hosts: 
      - "search-test:192.168.6.241"
      - "namenode:192.168.6.241"
      - "datanode:192.168.6.241"
      - "historyserver:192.168.6.241"
      - "resourcemanager:192.168.6.241"
    networks: 
      - hadoop

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8091:8081"
    environment:
      - "SPARK_MASTER=spark://search-test:7077"
      - "constraint:node==worker1"
    extra_hosts: 
      - "search-test:192.168.6.241"
      - "namenode:192.168.6.241"
      - "datanode:192.168.6.241"
      - "historyserver:192.168.6.241"
      - "resourcemanager:192.168.6.241"
    networks: 
      - hadoop

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8092:8081"
    environment:
      - "SPARK_MASTER=spark://search-test:7077"
      - "constraint:node==worker2"
    extra_hosts: 
      - "search-test:192.168.6.241"
      - "namenode:192.168.6.241"
      - "datanode:192.168.6.241"
      - "historyserver:192.168.6.241"
      - "resourcemanager:192.168.6.241"
    networks: 
      - hadoop

networks:
 hadoop:
  external:
   name: hadoop