services:
  redis-exporter:
      image: oliver006/redis_exporter
      container_name: redis-exporter
      ports:
        - 9121:9121
      networks:
        - public
      environment:
        - REDIS_ADDR=redis://10.0.0.1:6379
        - REDIS_PASSWORD=
        
networks:
  public:
    external: true